### ISSUE TITLE
How can I get this to work on the clientside?

### ISSUE THREAD

**Issue by 60percentCaffeine** [meepen/gmsv_mounter#1]
How can I get this to work on the clientside? I want that it mounts all content inside GarrysMod/garrysmod/somefolder/_/ (_ mean all folders inside this somefolder) before the GMOD menu starts. I'm not afraid of editing the GMOD Lua-files.

**Comment by meepen** [comment]
Mounts it where exactly? Like what id?

**Comment by 60percentCaffeine** [comment]
I want to make it work like the Legacy Addons system, but with ability to rewrite original game files.

**Comment by meepen** [comment]
Just build as normal, and put in lua/bin
You will have to hijack lua/menu/menu.lua and require and use the file library to mount all the paths you need to the correct ids such as "lcl", "lsv", "GAME", "MOD", and whatever else it needs to do.

**Comment by meepen** [comment]
Also note, if you want to do it serverside, you have to do it in lua/includes/init.lua
